spring:
  application:
    name: WeixinServe
serve:
  port: 8080
wechat:
  cp:
    corp-id: ww2867dedcc26777d3
    corp-secret: your_corp_secret
    agent-id: 1000011
    token: iLaYOUCANR576cE
    aes-key: iUdgqxK46Z8fxUhyhVWKHntoxe8S9ou37yGs9w2L49n